/**
 * CSS3 Stylesheet Generator
 *
 * Generates a responsive, typography-optimized CSS stylesheet
 * for ePub 3.0 documents. Includes special support for Korean text
 * (Hangul line-breaking, font stacks, vertical rhythm).
 */

export type CssTheme = 'default' | 'classic' | 'modern' | 'academic';

// ---------------------------------------------------------------------------
// Theme colour palettes
// ---------------------------------------------------------------------------

interface ThemeColors {
  background: string;
  text: string;
  heading: string;
  accent: string;
  link: string;
  blockquoteBg: string;
  blockquoteBorder: string;
  tableBorder: string;
  captionText: string;
}

const THEME_COLORS: Record<CssTheme, ThemeColors> = {
  default: {
    background: '#ffffff',
    text: '#1a1a1a',
    heading: '#111111',
    accent: '#2563eb',
    link: '#2563eb',
    blockquoteBg: '#f8f9fa',
    blockquoteBorder: '#dee2e6',
    tableBorder: '#dee2e6',
    captionText: '#6c757d',
  },
  classic: {
    background: '#faf8f0',
    text: '#2c2c2c',
    heading: '#1a1a1a',
    accent: '#8b4513',
    link: '#8b4513',
    blockquoteBg: '#f5f0e6',
    blockquoteBorder: '#c9b99a',
    tableBorder: '#c9b99a',
    captionText: '#7a7060',
  },
  modern: {
    background: '#ffffff',
    text: '#374151',
    heading: '#111827',
    accent: '#6366f1',
    link: '#6366f1',
    blockquoteBg: '#f3f4f6',
    blockquoteBorder: '#e5e7eb',
    tableBorder: '#e5e7eb',
    captionText: '#9ca3af',
  },
  academic: {
    background: '#ffffff',
    text: '#212529',
    heading: '#212529',
    accent: '#0d6efd',
    link: '#0d6efd',
    blockquoteBg: '#f1f3f5',
    blockquoteBorder: '#adb5bd',
    tableBorder: '#adb5bd',
    captionText: '#868e96',
  },
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generate a complete CSS3 stylesheet for ePub 3.0.
 *
 * @param theme - Colour theme to use
 * @returns CSS string
 */
export function generateStylesheet(theme: CssTheme = 'default'): string {
  const c = THEME_COLORS[theme] ?? THEME_COLORS.default;

  return `@charset "UTF-8";

/* =========================================================================
   ePub 3.0 Responsive Stylesheet
   Theme: ${theme}
   Generated by @gov-epub/core
   ========================================================================= */

/* -------------------------------------------------------------------------
   CSS Custom Properties (theme)
   ------------------------------------------------------------------------- */
:root {
  --color-bg: ${c.background};
  --color-text: ${c.text};
  --color-heading: ${c.heading};
  --color-accent: ${c.accent};
  --color-link: ${c.link};
  --color-blockquote-bg: ${c.blockquoteBg};
  --color-blockquote-border: ${c.blockquoteBorder};
  --color-table-border: ${c.tableBorder};
  --color-caption: ${c.captionText};

  /* Typography scale (modular, base 1rem = 16px) */
  --font-size-base: 1rem;
  --font-size-sm: 0.875rem;
  --font-size-lg: 1.125rem;
  --font-size-xl: 1.25rem;
  --font-size-2xl: 1.5rem;
  --font-size-3xl: 1.875rem;
  --font-size-4xl: 2.25rem;

  --line-height-base: 1.8;
  --line-height-heading: 1.3;

  --spacing-xs: 0.25rem;
  --spacing-sm: 0.5rem;
  --spacing-md: 1rem;
  --spacing-lg: 1.5rem;
  --spacing-xl: 2rem;
  --spacing-2xl: 3rem;
}

/* -------------------------------------------------------------------------
   Reset & Base
   ------------------------------------------------------------------------- */
*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

html {
  font-size: 100%;
  -webkit-text-size-adjust: 100%;
  text-size-adjust: 100%;
}

body {
  font-family:
    "Noto Sans KR", "Pretendard", "Apple SD Gothic Neo",
    "Malgun Gothic", "맑은 고딕",
    -apple-system, BlinkMacSystemFont,
    "Segoe UI", Roboto, "Helvetica Neue", Arial,
    sans-serif;
  font-size: var(--font-size-base);
  line-height: var(--line-height-base);
  color: var(--color-text);
  background-color: var(--color-bg);
  padding: var(--spacing-lg);
  max-width: 45em;
  margin: 0 auto;

  /* Korean text optimization */
  word-break: keep-all;
  overflow-wrap: break-word;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-rendering: optimizeLegibility;
  font-feature-settings: "kern" 1, "liga" 1;

  /* Hanging punctuation for CJK */
  hanging-punctuation: allow-end;
}

/* -------------------------------------------------------------------------
   Headings
   ------------------------------------------------------------------------- */
h1, h2, h3, h4, h5, h6 {
  font-family:
    "Noto Serif KR", "Pretendard", "Apple SD Gothic Neo",
    "Malgun Gothic", "맑은 고딕",
    Georgia, "Times New Roman", serif;
  color: var(--color-heading);
  line-height: var(--line-height-heading);
  margin-top: var(--spacing-2xl);
  margin-bottom: var(--spacing-md);
  font-weight: 700;
  page-break-after: avoid;
  break-after: avoid;
}

h1 {
  font-size: var(--font-size-4xl);
  margin-top: var(--spacing-xl);
  border-bottom: 2px solid var(--color-accent);
  padding-bottom: var(--spacing-sm);
}

h2 {
  font-size: var(--font-size-3xl);
}

h3 {
  font-size: var(--font-size-2xl);
}

h4 {
  font-size: var(--font-size-xl);
}

h5 {
  font-size: var(--font-size-lg);
}

h6 {
  font-size: var(--font-size-base);
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

/* -------------------------------------------------------------------------
   Paragraphs & Text
   ------------------------------------------------------------------------- */
p {
  margin-bottom: var(--spacing-md);
  text-align: justify;
  /* Korean text: slightly wider letter-spacing for readability */
  letter-spacing: -0.01em;
  orphans: 2;
  widows: 2;
}

p + p {
  text-indent: 1em;
}

/* -------------------------------------------------------------------------
   Links
   ------------------------------------------------------------------------- */
a {
  color: var(--color-link);
  text-decoration: underline;
  text-underline-offset: 0.15em;
}

a:hover,
a:focus {
  text-decoration-thickness: 2px;
}

/* -------------------------------------------------------------------------
   Blockquotes
   ------------------------------------------------------------------------- */
blockquote {
  margin: var(--spacing-lg) 0;
  padding: var(--spacing-md) var(--spacing-lg);
  background-color: var(--color-blockquote-bg);
  border-left: 4px solid var(--color-blockquote-border);
  font-style: italic;
}

blockquote p {
  text-indent: 0;
  margin-bottom: var(--spacing-sm);
}

blockquote p:last-child {
  margin-bottom: 0;
}

/* -------------------------------------------------------------------------
   Lists
   ------------------------------------------------------------------------- */
ul, ol {
  margin: var(--spacing-md) 0;
  padding-left: var(--spacing-xl);
}

li {
  margin-bottom: var(--spacing-xs);
}

li > ul,
li > ol {
  margin-top: var(--spacing-xs);
  margin-bottom: 0;
}

dl {
  margin: var(--spacing-md) 0;
}

dt {
  font-weight: 700;
  margin-top: var(--spacing-sm);
}

dd {
  margin-left: var(--spacing-lg);
  margin-bottom: var(--spacing-sm);
}

/* -------------------------------------------------------------------------
   Images & Figures
   ------------------------------------------------------------------------- */
figure {
  margin: var(--spacing-lg) 0;
  text-align: center;
  page-break-inside: avoid;
  break-inside: avoid;
}

img {
  max-width: 100%;
  height: auto;
  display: block;
  margin: 0 auto;
}

figcaption {
  margin-top: var(--spacing-sm);
  font-size: var(--font-size-sm);
  color: var(--color-caption);
  text-align: center;
  font-style: italic;
}

/* -------------------------------------------------------------------------
   Tables
   ------------------------------------------------------------------------- */
table {
  width: 100%;
  border-collapse: collapse;
  margin: var(--spacing-lg) 0;
  font-size: var(--font-size-sm);
  page-break-inside: avoid;
  break-inside: avoid;
}

th, td {
  border: 1px solid var(--color-table-border);
  padding: var(--spacing-sm) var(--spacing-md);
  text-align: left;
  vertical-align: top;
}

th {
  background-color: var(--color-blockquote-bg);
  font-weight: 700;
}

caption {
  caption-side: bottom;
  padding: var(--spacing-sm);
  font-size: var(--font-size-sm);
  color: var(--color-caption);
  text-align: left;
}

/* -------------------------------------------------------------------------
   Code & Preformatted
   ------------------------------------------------------------------------- */
pre {
  margin: var(--spacing-lg) 0;
  padding: var(--spacing-md);
  background-color: var(--color-blockquote-bg);
  border: 1px solid var(--color-table-border);
  border-radius: 4px;
  overflow-x: auto;
  font-size: var(--font-size-sm);
  line-height: 1.5;
}

code {
  font-family: "Noto Sans Mono", "D2Coding", "Consolas", "Monaco", monospace;
  font-size: 0.9em;
  background-color: var(--color-blockquote-bg);
  padding: 0.1em 0.3em;
  border-radius: 3px;
}

pre code {
  background: none;
  padding: 0;
  border-radius: 0;
}

/* -------------------------------------------------------------------------
   Cover Page
   ------------------------------------------------------------------------- */
[epub\\:type="cover"] {
  text-align: center;
  padding: 0;
}

[epub\\:type="cover"] figure {
  margin: 0;
}

[epub\\:type="cover"] img {
  max-height: 100vh;
  object-fit: contain;
}

/* -------------------------------------------------------------------------
   Section & Chapter Structure
   ------------------------------------------------------------------------- */
section[epub\\:type="chapter"] {
  page-break-before: always;
  break-before: page;
}

section[epub\\:type="chapter"] > header {
  margin-bottom: var(--spacing-xl);
}

/* -------------------------------------------------------------------------
   Footnotes & Endnotes
   ------------------------------------------------------------------------- */
aside[epub\\:type="footnote"],
aside[epub\\:type="endnote"] {
  font-size: var(--font-size-sm);
  border-top: 1px solid var(--color-table-border);
  margin-top: var(--spacing-lg);
  padding-top: var(--spacing-sm);
}

/* -------------------------------------------------------------------------
   Accessibility: focus visible
   ------------------------------------------------------------------------- */
:focus-visible {
  outline: 2px solid var(--color-accent);
  outline-offset: 2px;
}

/* -------------------------------------------------------------------------
   Print-friendly defaults for EPUB renderers
   ------------------------------------------------------------------------- */
@media print {
  body {
    background: #fff;
    color: #000;
  }

  a {
    color: #000;
    text-decoration: underline;
  }
}

/* -------------------------------------------------------------------------
   Responsive: smaller screens
   ------------------------------------------------------------------------- */
@media screen and (max-width: 600px) {
  body {
    padding: var(--spacing-md);
    font-size: 0.95rem;
  }

  h1 { font-size: var(--font-size-2xl); }
  h2 { font-size: var(--font-size-xl); }
  h3 { font-size: var(--font-size-lg); }

  table {
    font-size: 0.8rem;
  }

  th, td {
    padding: var(--spacing-xs) var(--spacing-sm);
  }
}
`;
}
